Repository tukasa0001/TownOfHost, pull requests merged in 2022-06, with the labels that each got.

#618 Change/ButtonText
  Patches/HudPatch.cs
  Resources/string.csv
  Roles/FireWorks.cs
Labels: new feature/新機能, change/仕様変更

#619 Change/DeleteKillButton
  Patches/HudPatch.cs
Labels: change/仕様変更

#624 Fix/ライター、スピードブースターでタスク完了しても能力発動しない
  Patches/PlayerContorolPatch.cs
  Patches/RecomputeTaskPatch.cs
Labels: bug/バグ修正

#621 エクスキューショナーが回線切断したときにDictionaryのKeyを削除するように
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#633 Feature/LighterNewSetting
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Resources/string.csv
Labels: new feature/新機能

#631 Fix/disconnect
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#635 Fix/bounty target
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#622 Fix/MayorPortableButton
  Modules/ExtendedPlayerControl.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正, change/仕様変更

#636 Feature/ArsonistDousingFix
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正, change/仕様変更

#638 ホストに続けてロビーに戻った際に落ちる問題を修正
  Modules/RPC.cs
Labels: bug/バグ修正

#610 change/NeutralInfo
  Patches/IntroPatch.cs
  Resources/string.csv
Labels: change/仕様変更

#641 呪殺時にSetDeadをしていなかったため、生存と表示される問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#642 スニッチの矢印をタスク中のみ更新
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#643 エンジニアと科学者のカラー変更
  main.cs
Labels: change/仕様変更

#645 SniperとFireWorksのログ抑制
  Roles/FireWorks.cs
  Roles/Sniper.cs
Labels: change/仕様変更

#644 クルー勝利時のテキストカラーをエンジニアに変更
  Patches/OutroPatch.cs
Labels: change/仕様変更

#626 Feature/ApplyResetAbilityCooldown
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  README.md
  Resources/string.csv
Labels: new feature/新機能

#616 /templateコマンドを追加
  Patches/ChatCommandPatch.cs
Labels: new feature/新機能

#651 メソッドを改名
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Patches/GameStartManagerPatch.cs
Labels: change/仕様変更

#653 メッセージの個別送信を修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#650 Fix/sniper document
  README-EN.md
  README.md
Labels: documentation/文書の変更

#658 Warlockが呪いキルできない問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#659 アーソニストの塗りマークをホストにも表示
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#660 一部役職がマッドメイト化で暗転する問題を修正
  Patches/MeetingHudPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正

#661 タイムシーフの仕様変更
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: change/仕様変更

#656 Fix/Arsonist-Dictionaries
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: Refactoring/リファクタリング

#670 NotifyRolesを修正
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
Labels: bug/バグ修正, change/仕様変更

#671 メッセージの表示間隔の設定
  Patches/ChatCommandPatch.cs
  README-EN.md
  README.md
  main.cs
Labels: new feature/新機能

#674 ボタン回数同期モードで余計に消費される問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#677 リリース一覧を簡素化
  README-EN.md
  README.md
Labels: documentation/文書の変更

#675 StandardHASで、サボタージュを無効化
  Patches/ShipStatusPatch.cs
Labels: invalid/無効

#682 Mareの説明が表示されない問題を修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#683 不正なRPCを送るプレイヤーをキック
  Modules/RPC.cs
Labels: change/仕様変更

#678 インポスター勝利時にエゴイストを守護天使に、エゴイスト勝利時にインポスターを守護天使に置き換えるように
  Patches/CheckGameEndPatch.cs
Labels: change/仕様変更

#685 /now rolesコマンドを追加
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
Labels: new feature/新機能

#694 バウンティでターゲットが連続で同じになる問題を改善
  Modules/ExtendedPlayerControl.cs
Labels: change/仕様変更

#697 推奨設定を復活&調整
  Patches/GameOptionsMenuPatch.cs
Labels: change/仕様変更

#695 Fix/arrow when dead
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#698 TOHオプション画面でCtrl+Deleteを押すとすべてデフォルト値に
  Patches/ControlPatch.cs
  Patches/GameOptionsMenuPatch.cs
Labels: new feature/新機能

#687 いつでも会議メソッドを作成
  Modules/ExtendedPlayerControl.cs
  Patches/ControlPatch.cs
Labels: new feature/新機能

#691 バニラ役職の設定画面で役職名に色付け
  Patches/GameOptionsPatch.cs
Labels: new feature/新機能

#700 ロビーに戻った際に下に移動し続ける問題を修正
  Patches/HudPatch.cs
Labels: bug/バグ修正

#701 READMEを修正
  README-EN.md
  README.md
Labels: documentation/文書の変更

#669 Revert/DefaultKillCooldown
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ExilePatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Resources/string.csv
Labels: bug/バグ修正, change/仕様変更

#702 READMEの不要なテキストを削除
  README-EN.md
  README.md
Labels: documentation/文書の変更

#704 ルームコード自動貼り付けの条件を修正
  Patches/JoinGameButtonPatch.cs
Labels: bug/バグ修正

#706 コマンドを追加
  Patches/ChatCommandPatch.cs
Labels: new feature/新機能

#705 AfterMeetingTasksで辞書重複の例外を修正
  Modules/Utils.cs
Labels: bug/バグ修正

#712 RpcVersionCheckで稀にキックされる問題を修正
  Modules/RPC.cs
Labels: bug/バグ修正, change/仕様変更

#710 マッドメイトを作れる残り数を表示
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
Labels: new feature/新機能

#715 Feature/CustomRpcSender
  Modules/CustomRpcSender.cs
  Patches/ControlPatch.cs
Labels: new feature/新機能

#717 翻訳のキーを改名
  Modules/Utils.cs
  Resources/string.csv
Labels: change/仕様変更

#709 /now rolesでバニラ役職が表示できない問題を修正
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
Labels: bug/バグ修正

#719 SetNameの軽量化
  Modules/RPC.cs
  Modules/Utils.cs
Labels: Refactoring/リファクタリング, change/仕様変更

#726 VoteModeが有効じゃなくても一覧に表示される問題を修正
  Modules/Utils.cs
Labels: bug/バグ修正

#725 名前の位置が下にずれる問題を修正
  Modules/Utils.cs
Labels: bug/バグ修正

#724 会議で名前にボタンの残り回数を表示しない
  Patches/ChatCommandPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#723 日本語がペーストできない問題を修正
  Patches/ChatControlPatch.cs
Labels: bug/バグ修正

#727 Dictatorが最後に投票するとDictatorだけ死ぬ問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#729 DictatorがBANされる問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#730 PadRightV2で例外が発生する問題を修正
  Modules/Utils.cs
Labels: bug/バグ修正

#731 切断ラバーズの相方が生き残ってもラバーズ勝利になる問題を修正
  Patches/OutroPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#732 Warlockのキル後に変身クールが長い問題を修正
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#734 HideGameCodesを翻訳
  Patches/ClientOptionsPatch.cs
  Resources/string.csv
Labels: change/仕様変更

#733 シェイプシフトのアイコンが消える問題を修正
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#736 処刑用のコマンドを追加
  Patches/MeetingHudPatch.cs
Labels: new feature/新機能

#711 チャット送信履歴機能
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  README-EN.md
  README.md
Labels: new feature/新機能

#728 クライアントでも/templateコマンドが使えるように
  Patches/ChatCommandPatch.cs
Labels: change/仕様変更

#721 Change/VanillaRole_LoversIntro
  Modules/Utils.cs
  Patches/IntroPatch.cs
Labels: change/仕様変更

#646 Doc/README
  README-EN.md
  README.md
Labels: documentation/文書の変更

#738 ウィッチがスペルモードでキルできてしまう問題を修正
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#740 キルクールが勝手に0秒になる問題を修正
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#741 READMEを復元
  README-EN.md
Labels: documentation/文書の変更

#742 READMEを整理
  README-EN.md
  README.md
Labels: documentation/文書の変更

#744 EndGameに特殊勝利を集約
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
Labels: Refactoring/リファクタリング

#743 会議中の死亡タイミングを追放処理完了後に変更
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: change/仕様変更

#747 SuffixModesを翻訳
  Modules/Utils.cs
Labels: bug/バグ修正

#748 ColorNameModeを追加
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#754 死因「処刑」を追加
  Modules/GameState.cs
  Patches/MeetingHudPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#752 ColorNameModeで、ホスト以外がRpcSetNameを実行してBANされる問題を修正
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#751 キルクールリセットをカウントダウン時のみに制限
  Modules/OptionHolder.cs
  Patches/GameStartManagerPatch.cs
Labels: bug/バグ修正

#757 AfterMeetingDeathPlayersがクリアされない問題を修正
  Patches/ExilePatch.cs
Labels: bug/バグ修正

#756 MODクライアントでミーティング時ロールが表示されない問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#758 GetRoleChanceが1か0になってしまう問題を修正
  Modules/OptionHolder.cs
Labels: bug/バグ修正

#759 試合結果に勝利陣営を表示
  Modules/Utils.cs
  Patches/OutroPatch.cs
  Resources/string.csv
Labels: change/仕様変更

#767 Fix/find closest target
  Patches/HudPatch.cs
Labels: EmergencyFix/緊急バグ修正

#768 本体アップデートの修正
  Patches/HudPatch.cs
Labels: EmergencyFix/緊急バグ修正

#771 シュレディンガーの猫をキルした後にシリアルキラーの自滅時間が戻らないバグを修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#770 mainへのマージ (v2.1.0)
  Modules/CustomRolesHelper.cs
  Modules/CustomRpcSender.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/ModUpdater.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ChatControlPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: merge to main/メインへのマージ

#772 Feature/NewVanillaButtonPosition
  Patches/ClientOptionsPatch.cs
Labels: new feature/新機能, change/仕様変更

#774 FindClosestTargetで例外が出る問題を修正
  Patches/HudPatch.cs
Labels: bug/バグ修正

#686 Fix/WarlockKillBan
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Roles/FireWorks.cs
Labels: bug/バグ修正

#779 Discordボタンの座標を修正
  Modules/ModUpdater.cs
Labels: bug/バグ修正

#782 キルクール関係を修正
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#786 バージョンを2.1.1に変更
  main.cs
Labels: VerUp/バージョンアップ

#787 ホストが死んでいると処刑コマンドを使えない問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#783 チャットの送信制限を改善
  Patches/ChatCommandPatch.cs
Labels: change/仕様変更

#790 Fix/OverrideTasksData
  Modules/OptionHolder.cs
Labels: bug/バグ修正

#789 Feature/FindClosestTarget-Fix
  Patches/HudPatch.cs
  Patches/onGameStartedPatch.cs
Labels: change/仕様変更

#796 HideAndSeekの仕様変更
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: change/仕様変更

#797 RpcSetRoleReplacerを一度RPCを貯めてから書き込むよう変更
  Patches/onGameStartedPatch.cs
Labels: new feature/新機能

#798 Change/find closest targets 2nd fix
  Patches/HudPatch.cs
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正, change/仕様変更

#802 死亡後に会議時間を返す/返さないオプションを追加
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Resources/string.csv
Labels: new feature/新機能

#800 オートミュートで部屋コードがおかしくなる問題を修正
  Patches/GameStartManagerPatch.cs
Labels: bug/バグ修正

#799 PingTrackerに情報を表示
  Patches/CredentialsPatch.cs
  Resources/string.csv
Labels: new feature/新機能, change/仕様変更

#805 マフィアを通常インポスターに変更
  Modules/OptionShower.cs
  Patches/GameOptionsPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: change/仕様変更

#811 Fix/ClashByInvite(プレイヤー招待時のBANの修正)
  Patches/HudPatch.cs
Labels: bug/バグ修正

#807 CustomRoles派生のIsCrewmateを作成
  Modules/CustomRolesHelper.cs
Labels: new feature/新機能

#808 SteanerModeにHideCodesを統合
  Patches/ClientOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  main.cs
Labels: new feature/新機能, change/仕様変更
