Repository tukasa0001/TownOfHost, pull requests merged in 2022-03, with the labels that each got.

#280 Fix/option tab
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/RPC.cs
  Patches/ControlPatch.cs
  Patches/HudPatch.cs
  Patches/TaskAssignPatch.cs
  Resources/string.csv
Labels: bug/バグ修正

#284 オプションタグの修正と、守護天使バグの対応
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionController.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: bug/バグ修正

#287 SKMadmate作成時にRPCで通知するように修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#283 [to Option Tab]sub role
  Modules/Calculation.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: new role/新役職, new feature/新機能

#294 feature/NewSheriffOption
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ControlPatch.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#291 Feature/schrodingercat_pp
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#297 Feature/terorist win renew v1.4
  Modules/GameState.cs
  Patches/ExilePatch.cs
  main.cs
Labels: bug/バグ修正, new feature/新機能

#298 Fix/TerroristWin
  Modules/Utils.cs
  Patches/ExilePatch.cs
Labels: bug/バグ修正

#266 Fix/client-exceptions-v1.5
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#295 Feature/retryarsonist
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#301 confingidの修正
  Modules/OptionHolder.cs
Labels: bug/バグ修正
