Repository tukasa0001/TownOfHost, pull requests merged in 2022-04, with the labels that each got.

#309 ボタン位置を調節
  Patches/ClientOptionsPatch.cs
Labels: bug/バグ修正

#310 ボタン位置の調整
  Patches/ClientOptionsPatch.cs
Labels: bug/バグ修正

#307 Fix/broken update(v1.4)
  Patches/ClientOptionsPatch.cs
  Patches/ControlPatch.cs
  Patches/IntroPatch.cs
  TownOfHost.csproj
  main.cs
Labels: bug/バグ修正

#315 [v1.4]試合中に/lastrolesが使えなくなるように変更
  main.cs
Labels: new feature/新機能

#313 不要なListを削除
  Patches/ControlPatch.cs
Labels: documentation/文書の変更

#314 JapaneseRoleNameの位置を修正
  Patches/ClientOptionsPatch.cs
Labels: bug/バグ修正

#318 [v1.4]Limit_Lastroles_return
  main.cs
Labels: new feature/新機能

#311 [v1.5]オプションの位置変更
  Patches/ClientOptionsPatch.cs
Labels: bug/バグ修正

#322 Feature/addVanillaToNowCommand_v1.4
  main.cs
Labels: new feature/新機能

#316 [v1.5]試合中に/lastrolesを使用できないように変更
  Modules/Utils.cs
Labels: new feature/新機能

#300 RPC追加
  Modules/RPC.cs
Labels: bug/バグ修正

#324 feature/Egoist
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#290 feature/Watcher_Remake
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#299 Feature/SpeedBooster
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Patches/HudPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#329 feature/New_SchrodingerCat_Setting
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ExilePatch.cs
  Resources/string.csv
Labels: new feature/新機能

#333 RoleTypeに変更
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Patches/IntroPatch.cs
  Patches/OutroPatch.cs
  Patches/TaskAdderPatch.cs
Labels: documentation/文書の変更

#292 feature/LastImpostor_Remake
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職, new feature/新機能

#337 Fix/onGameStartPatch_v1.4
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#302 Feature/VisibleSheriffShotLimit
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
Labels: new feature/新機能

#340 [v1.4]オンラインでマップを切り替えられるように修正
  Modules/CustomOptions.cs
Labels: bug/バグ修正

#341 [v1.5]オンラインでマップを切り替えられるように修正
  Patches/GameOptionsMenuPatch.cs
Labels: bug/バグ修正

#304 [v1.5]fix/bountyhunter vampire
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/PlayerContorolPatch.cs
  Resources/string.csv
Labels: bug/バグ修正

#323 [v1.5]Feature/add vanilla to now command v1.5
  Modules/CustomRolesHelper.cs
  Modules/Utils.cs
  main.cs
Labels: new feature/新機能

#326 [v1.5]エアシップで発生していた問題を修正
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正

#343 [v1.5]fix/LobbyNameColor
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#346 [v1.5]Fix/sync custom settings rpc read write
  Modules/CustomOption.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
Labels: bug/バグ修正

#265 [v1.5][1]Feature/version-checker-v1.5
  Helpers.cs
  Modules/RPC.cs
  Patches/PlayerJoinAndLeftPatch.cs
  main.cs
Labels: new feature/新機能

#350 [v1.5]CursedPlayerDieからCursedPlayers.Valuesに変数を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#352 [v1.4]ヴァンパイアのキルクールが正常に動作するように変更
  Patches/ExilePatch.cs
  Patches/ShipStatusPatch.cs
  main.cs
Labels: bug/バグ修正

#349 Refact/Re_CTDictionary
  Modules/ExtendedPlayerControl.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: Refactoring/リファクタリング

#354 [v1.5]invalid/HAS_IgnoreCosmetics
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Patches/onGameStartedPatch.cs
Labels: invalid/無効

#353 [v1.4]invalid/HAS_IgnoreCosmetics
  Modules/OptionController.cs
Labels: invalid/無効

#356 Fix/EgoistWin
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#358 [v1.5]Fix/witch-symbol-v1.5
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#359 [v1.5]ホストの会議画面時のタスク表示の括弧が二重になっていた問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#361 [v1.4]Refact/logger-tag-v1.4
  Modules/ExtendedPlayerControl.cs
  Modules/LateTask.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Refactoring/リファクタリング

#355 [v1.5]Feature/current preset
  Modules/CustomOption.cs
Labels: new feature/新機能

#364 [v1.5]Fix/current preset
  Modules/CustomOption.cs
Labels: bug/バグ修正

#365 [v1.4]Feature/better-logs-v1.4
  Modules/LateTask.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: new feature/新機能, Refactoring/リファクタリング

#368 [v1.4]ヴァンパイアのキル時のログを修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#372 [v1.4]Fix/vote-log-exception
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#373 [v1.5][1]refact/TaskText
  Patches/HudPatch.cs
Labels: Refactoring/リファクタリング

#374 [v1.5][2]Refact/HudPatch
  Patches/HudPatch.cs
Labels: Refactoring/リファクタリング

#375 Fix/LastImpostor
  Modules/ExtendedPlayerControl.cs
  Resources/string.csv
Labels: bug/バグ修正

#376 [v1.5]Fix/HudPatch
  Patches/HudPatch.cs
Labels: bug/バグ修正

#366 [v1.5]Feature/detect-csv-error
  Modules/Translator.cs
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#377 [v1.5]OnとOffがINVALIDと表示されるのを修正
  Resources/string.csv
Labels: bug/バグ修正

#371 [v1.5]Feature/Trapper
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#382 [v1.4]デバッグモード時はスプラッシュをスキップするように
  Patches/ClientPatch.cs
Labels: new feature/新機能

#381 [v1.5]デバッグモード時はスプラッシュをスキップするように
  Patches/ClientPatch.cs
Labels: new feature/新機能

#385 Fix/set is dead in murder player
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#370 [v1.4]Fix/spelled kill v1.4
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#387 [v1.5]RpcVersionCheckの遅延秒数を修正
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#388 [v1.5]Fix/client-exception-v1.5
  Patches/HudPatch.cs
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#386 [v1.5]LateTaskの例外ログにスタックトレースを追加
  Modules/LateTask.cs
Labels: Refactoring/リファクタリング

#389 [v1.4]fix/vote-logs
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#392 [v1.4]Fix/vanpire meeting
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#396 [v1.4]VersionCheckからベータバージョンの項目を削除
  Modules/RPC.cs
Labels: bug/バグ修正

#400 Fix/BanButtonStuck-1.5
  Patches/HideBanButtonPatch.cs
Labels: bug/バグ修正

#399 Fix/BanButtonStuck
  Patches/HideBanButtonPatch.cs
Labels: bug/バグ修正

#398 [v1.5]Fix/version-check-delay
  Modules/RPC.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#393 [v1.4]VersionNumberUp
  TownOfHost.csproj
  main.cs
Labels: documentation/文書の変更

#395 [v1.5]versioning
  TownOfHost.csproj
  main.cs
Labels: documentation/文書の変更

#401 [v1.5]Fix/has-wait-time-v1.5
  Patches/IntroPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正

#404 [v1.4]fix/getVoteName
  Patches/PlayerJoinAndLeftPatch.cs
  main.cs
Labels: bug/バグ修正

#406 [v1.4]Fix/client-logs
  Patches/HudPatch.cs
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#405 [v1.4]Fix/control-patch-exception-v1.4
  Patches/ControlPatch.cs
Labels: bug/バグ修正

#407 [v1.4]ダンプファイル名を修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#409 [v1.4]スキップや無投票がinvalidと表示される問題を修正
  main.cs
Labels: bug/バグ修正

#412 [v1.4]バージョンが取得できなかった際の例外処理を追加
  Modules/RPC.cs
Labels: bug/バグ修正

#411 [v1.5]アーソニスト勝利時に守護天使に置き換えないように変更
  Patches/CheckGameEndPatch.cs
Labels: change/仕様変更

#415 [v1.5]fix/dump-command-v1.5
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#410 [v1.5]ロビーでOptionShowerが表示されていないバグを修正
  Patches/HudPatch.cs
Labels: bug/バグ修正

#421 Remove/beta-functions-v1.5
  Helpers.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ClientPatch.cs
  Patches/CredentialsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
  main.cs
Labels: removed/機能削除

#419 [v1.5]Feature/GameStates-class
  Modules/GameState.cs
Labels: new feature/新機能

#416 [v1.4]Fix/control-patch-exception-v1.4
  Patches/ControlPatch.cs
Labels: bug/バグ修正

#422 [v1.5]シェリフ以外のCheckProtectもすべてfalseで返していた問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#425 [v1.5]Refact/VersionCheck
  Helpers.cs
  Modules/RPC.cs
Labels: Refactoring/リファクタリング

#427 Change/readme
  README-EN.md
  README.md
Labels: documentation/文書の変更

#429 v1.4をmainにマージ
  .gitignore
  BAN-MEMO.md
  DebugWebhookSender.cs
  Helpers.cs
  Images/TownOfHost HideCode.png
  Images/TownOfHost-Discord.png
  Images/TownOfHost-Title.png
  Modules/CustomOptions.cs
  Modules/CustomRolesHelper.cs
  Modules/Debugger.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/LateTask.cs
  Modules/NameColorManager.cs
  Modules/OptionController.cs
  Modules/RPC.cs
  Modules/TextureManager.cs
  Modules/Translator.cs
  OptionController.cs
  Patches/ChatBubblePatch.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ClientPatch.cs
  Patches/ControlPatch.cs
  Patches/CredentialsPatch.cs
  Patches/DisconnectPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HideBanButtonPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/NoBlackoutPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/UnrestrictNumImpostor.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  RPC.cs
  Resources/TownOfHost-Logo.png
  TownOfHost-Title.jpg
  TownOfHost.csproj
  main.cs
Labels: Next Version/次期バージョン

#424 [v1.5]Refact/task state
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/Utils.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/ShipStatusPatch.cs
  main.cs
Labels: Refactoring/リファクタリング

#362 [v1.5]Fix/spelld kill
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#439 EndGameにnullチェックを追加
  Modules/RPC.cs
Labels: bug/バグ修正

#436 Change/readme-v2.0.0
  README-EN.md
  README.md
Labels: documentation/文書の変更

#440 [2.0.0]Fix/ModClientException
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#441 イビルウォッチャーがisImpostorに入っていない問題を修正
  Modules/CustomRolesHelper.cs
Labels: bug/バグ修正

#369 [v2.0.0] Refact/SwitchSystem
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
Labels: Refactoring/リファクタリング

#448 [v2.0.0]fix/SetNameRpc
  Modules/RPC.cs
Labels: bug/バグ修正

#443 [v2.0.0]送信しているRPCのログを出力
  Modules/RPC.cs
  main.cs
Labels: new feature/新機能

#451 [v2.0.0]Feature/ReduceNameNotify
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: new feature/新機能, Refactoring/リファクタリング
