Repository tukasa0001/TownOfHost, pull requests merged in 2022-09, with the labels that each got.

#1065 Change/SummaryTextPos
  Modules/Utils.cs
  Patches/OutroPatch.cs
Labels: bug/バグ修正, change/仕様変更

#1066 チャットでのロール割り当て確率がおかしい問題を修正
  Modules/OptionHolder.cs
Labels: bug/バグ修正

#1067 バウンティがバウンティターゲットの猫を切ったときに陣営が変化しない問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#1068 試合結果で例外が出る問題を修正
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#1069 同数投票時のオプションを追加
  Modules/OptionHolder.cs
  Patches/MeetingHudPatch.cs
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#1053 AfterMeetingDeathに含まれているプレイヤー全員にターゲットチェックを追加
  Modules/ExtendedPlayerControl.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#1073 refact/AssignDesyncRole
  Patches/onGameStartedPatch.cs
Labels: Refactoring/リファクタリング

#1075 Fix/ShowLastResult
  Modules/Utils.cs
Labels: bug/バグ修正

#1057 GMの湧き画面をスキップするように
  Patches/AirshipStatus.cs
Labels: change/仕様変更

#1074 Change/ResetAbilityCooldown
  Modules/ExtendedPlayerControl.cs
  Patches/GameOptionsPatch.cs
  Resources/string.csv
Labels: bug/バグ修正, change/仕様変更

#1070 エゴイスト、ジャッカルのスニッチマーク修正
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#1071 Feature/ExecutionerTargetOption
  Modules/OptionHolder.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#1072 エゴイスト勝利時の勝利者リスト修正
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Roles/TeamEgoist.cs
Labels: bug/バグ修正

#1079 ChangeExecutionerRole関係で発生するビルドエラーを修正
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Roles/Executioner.cs
Labels: EmergencyFix/緊急バグ修正

#1080 fix/SetTargetRpc
  Roles/Executioner.cs
Labels: bug/バグ修正

#1077 Refact/CustomWinner
  Modules/CustomWinnerHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Egoist.cs
  Roles/Executioner.cs
  Roles/TeamEgoist.cs
  main.cs
Labels: Refactoring/リファクタリング

#1086 AllAliveMeetingが死者が切断されているときに全員生存と判定する問題を修正
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#1085 CustomOptionのIDの重複ログを追加
  Modules/CustomOption.cs
Labels: duplicate/重複

#1084 チャットコマンドを追加
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
Labels: new feature/新機能

#1083 コミュサボ解除の条件を修正
  Modules/DisableDevice.cs
  Modules/Utils.cs
Labels: bug/バグ修正

#1087 ミーティングでロールが表示されない問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#1089 Fix/TerminateEndGame
  Patches/CheckGameEndPatch.cs
Labels: Fix/修正

#1091 環境出力が例外を吐く問題の対応
  Patches/IntroPatch.cs
Labels: bug/バグ修正

#1093 README_en への導線追加
  README.md
Labels: documentation/文書の変更

#1095 戻り値を自動で三項演算子に変換しないように修正
  .editorconfig
Labels: Fix/修正

#1096 不要なusingを削除
  Modules/CustomWinnerHolder.cs
  Modules/DisableDevice.cs
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatBubblePatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/LadderPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Roles/SabotageMaster.cs
  Roles/SerialKiller.cs
Labels: Refactoring/リファクタリング

#1078 Feature/EvilTracker&Seer
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  README_SChinese.md
  Resources/string.csv
  Roles/EvilTracker.cs
  main.cs
Labels: new role/新役職, new feature/新機能

#1100 誤字脱字修正&変数名の微修正
  Modules/GameState.cs
  Modules/ModUpdater.cs
  Modules/Utils.cs
  Patches/LadderPatch.cs
  Patches/OutroPatch.cs
  Roles/Sheriff.cs
  Roles/Sniper.cs
  main.cs
Labels: Fix/修正

#1040 ベントを使えるかの処理をswitch文に書き換え
  Patches/UsablesPatch.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#1090 Feature/NewMadSnitchSettings
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: new feature/新機能

#1092 doc/ForkGuideline
  ForkGuideline.md
Labels: documentation/文書の変更

#1103 AllAliveMeetingで死亡者が切断すると死亡してない扱いになる問題を修正
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#1104 IntroDestroyが実行される前に廃村したときに出るエラーを修正
  Patches/IntroPatch.cs
Labels: bug/バグ修正

#1102 Refact/Translation
  Modules/OptionHolder.cs
  Resources/string.csv
  Roles/Egoist.cs
  Roles/SerialKiller.cs
  Roles/Sheriff.cs
  Roles/TimeThief.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#1060 fix/RoleClass_Add_UnHostMod
  Modules/RPC.cs
  Patches/onGameStartedPatch.cs
  Roles/BountyHunter.cs
  Roles/TimeThief.cs
Labels: bug/バグ修正

#1105 ホストがキルフラッシュをすると全員に見えてしまう問題を修正
  Modules/Utils.cs
Labels: bug/バグ修正

#1110 追加の緊急ボタンクールダウンのオプション追加
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Resources/string.csv
Labels: new feature/新機能

#1109 ランダムスポーンをすべてのマップに適応
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: change/仕様変更

#1111 Airshipで初手会議前にキルできない問題を修正
  Patches/IntroPatch.cs
  Patches/RandomSpawnPatch.cs
Labels: bug/バグ修正

#1112 チャットの試合結果が見づらい問題を修正
  Modules/Utils.cs
Labels: Fix/修正

#1116 転落死のレート判定の修正。5％の追加
  Modules/CustomOption.cs
  Modules/OptionHolder.cs
  Patches/LadderPatch.cs
  Resources/string.csv
Labels: bug/バグ修正, new feature/新機能

#1122 /hidenameコマンドを追加
  Patches/ChatCommandPatch.cs
Labels: new feature/新機能

#1121 Suffixを追加
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Resources/string.csv
  main.cs
Labels: change/仕様変更

#1119 ホストは死んでいてもキックとBANを可能に
  Patches/ClientPatch.cs
Labels: change/仕様変更

#1120 タスク勝利の無効化オプション
  Modules/OptionHolder.cs
  Patches/CheckGameEndPatch.cs
  Patches/ShipStatusPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#1117 カスタム翻訳ファイル機能を追加
  Modules/Translator.cs
  Patches/ControlPatch.cs
Labels: new feature/新機能

#1114 初期スポーン時のクールダウンを修正するオプション
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#1127 テンプレートでコロンが表示できない問題を修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#1124 イビルトラッカーのターゲット設定不可時変身クールダウンを255秒に
  Modules/ExtendedPlayerControl.cs
  Roles/EvilTracker.cs
Labels: change/仕様変更

#1130 マッドスニッチのハリボテオプションを修正
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#1129 マッドメイトの追加オプション
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Resources/string.csv
Labels: new feature/新機能

#1131 RUS Translation Update
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1132 Fix/SnitchKnowsNeutralKiller
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#1133 ミーティング中のBGMをミュート
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: change/仕様変更

#1134 画面サイズ変更時に例外を吐く問題を修正
  Modules/ModUpdater.cs
Labels: bug/バグ修正

#1136 Update SChinese csv
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1139 ラストインポスター属性の表示を修正
  Modules/Utils.cs
Labels: Fix/修正

#1138 複数キー押しの検出メソッドの作成、適用
  Patches/ControlPatch.cs
Labels: Refactoring/リファクタリング

#1043 ジャッカル README
  README-EN.md
  README.md
Labels: documentation/文書の変更

#1141 解像度に1920x1080を追加
  Patches/ControlPatch.cs
Labels: Ajustment/調整

#1143 ローカルゲームで壁抜けが出来るように変更
  Patches/HudPatch.cs
Labels: change/仕様変更

#1144 CustomOptionsのGetBoolの改善
  Modules/CustomOption.cs
Labels: change/仕様変更

#1145 Feature/NoDelayEndGame
  Patches/CheckGameEndPatch.cs
Labels: Adjustment/調整

#1146 クライアントオプションのボタン位置を少し下に調整
  Patches/ClientOptionsPatch.cs
Labels: Adjustment/調整

#1147 Rus Translation Update
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1140 Fix/CustomWinnerHolder
  Modules/CustomWinnerHolder.cs
  Modules/Utils.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Roles/Executioner.cs
Labels: bug/バグ修正

#1148 Improved SChinese Translation
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1150 カスタム翻訳ファイルに無効なキーで発生する例外を修正
  Modules/Translator.cs
Labels: bug/バグ修正

#1149 DisableAdminのオプションを細分化
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/Devices/Admin.cs
  Resources/string.csv
Labels: change/仕様変更

#1151 TieModeの翻訳を修正
  Resources/string.csv
Labels: Fix/修正

#1152 SChinese scv update
  Resources/string.csv
Labels: Document/文書の変更

#1154 RusTranslation Update
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1153 カメラ・ドアログ・バイタル制限を追加
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/Devices/Admin.cs
  Resources/string.csv
Labels: New Feature/新機能, change/仕様変更

#1155 SChinese update
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1159 ロシア語を一番右に移動
  Resources/string.csv
Labels: Document/文書の変更, change/仕様変更

#1158 Executioner.csのCopyrightテキストを削除
  Roles/Executioner.cs
Labels: Document/文書の変更

#1160 コードのリファクタリング
  .editorconfig
  Modules/AntiBlackout.cs
  Modules/CustomRpcSender.cs
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientPatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/LadderPatch.cs
  Patches/OutroPatch.cs
  Patches/RandomSpawnPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Executioner.cs
  main.cs
Labels: Refactoring/リファクタリング

#1161 SChinese Update
  Resources/string.csv
Labels: Add Translation/翻訳追加

#1162 LoversSuicideをFollowingSuicideに変更
  Modules/GameState.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Resources/string.csv
  Roles/EvilTracker.cs
Labels: Document/文書の変更, change/仕様変更

#1164 全機器無効化ができたため一部説明を削除
  Resources/string.csv
Labels: Document/文書の変更, Fix/修正

#1123 Doc/UpdateREADME
  Images/MIRA_HQ_Random_Map.png
  Images/Mira_HQ_Random_Map.png
  Images/Polus_Random_Map.png
  Images/The_Airship_Random_Map.png
  Images/The_Skeld_Random_Map.png
  README-EN.md
  README.md
  Resources/string.csv
Labels: Document/文書の変更

#1166 Fix/conflict
  TownOfHost.csproj
  main.cs
Labels: Fix/修正

#1168 ジャッカルのREADMEが1つ改行されていない問題を修正
  README.md
Labels: Fix/修正
