Repository tukasa0001/TownOfHost, pull requests merged in 2022-07, with the labels that each got.

#816 カラーコード+stringでHelpers.ColorStringを使うように
  Modules/ExtendedPlayerControl.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ClientPatch.cs
  Patches/CredentialsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Roles/Sniper.cs
Labels: documentation/文書の変更

#817 ハシゴからの転落死機能を追加
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/LadderDeathPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: new feature/新機能

#821 2.2.0にアップデート
  main.cs
Labels: VerUp/バージョンアップ

#823 Fix/ProgressText
  Modules/Utils.cs
Labels: bug/バグ修正

#824 エクスキューショナーのターゲットが抜けたときに役職を変更し忘れていた問題を修正
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#822 mainへマージ
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ChatControlPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ClientPatch.cs
  Patches/ControlPatch.cs
  Patches/CredentialsPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HudPatch.cs
  Patches/LadderDeathPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  Roles/Sniper.cs
  main.cs
Labels: merge to main/メインへのマージ

#825 Fix/Re_ProgressText
  Modules/Utils.cs
  Roles/Sniper.cs
Labels: bug/バグ修正

#837 タイムシーフが心中した後に会議時間を戻すように
  Patches/ExilePatch.cs
Labels: bug/バグ修正

#845 花火職人の英語のイントロを修正
  Resources/string.csv
Labels: documentation/文書の変更

#838 切断したプレイヤーは第二ループを処理しないように
  Modules/Utils.cs
Labels: bug/バグ修正, change/仕様変更

#830 configにキルクールを保存するように
  Patches/GameStartManagerPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  main.cs
Labels: bug/バグ修正

#843 インポスター役職のシェイプシフトクールダウンを一括割り当て
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正, change/仕様変更

#847 Re:エクスキューショナーのターゲットが抜けたときにエクスキューショナーの役職を変更
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#851 Re:Re:YouAreTextを役職色にカラーリング
  Patches/IntroPatch.cs
Labels: change/仕様変更

#831 SetImpostorForServerを差し戻し
  Patches/IntroPatch.cs
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正, Critical Bug/重大なバグ

#853 Fix/FindClosestTarget_5th
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#855 ストリーマーモード有効時にオートミュートのコードがおかしい問題を修正
  Patches/GameStartManagerPatch.cs
Labels: bug/バグ修正

#856 バウンティーハンターがマッドメイトを作れないように修正
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#858 ゲーム開始時にクールダウンをリセット
  Patches/IntroPatch.cs
Labels: bug/バグ修正

#844 RoleSummary表示時に名前色を着色
  Modules/Utils.cs
  Patches/OutroPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: new feature/新機能

#835 名前にmodがついているときは公開部屋にできないように
  Patches/ClientPatch.cs
  Patches/GameStartManagerPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#860 ウェルカムメッセージを追加
  Patches/ChatCommandPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  README-EN.md
  README.md
Labels: new feature/新機能

#862 2.2.1へアップデート
  main.cs
Labels: VerUp/バージョンアップ

#859 [2.2.1後]役職Desyncをメソッド化
  Patches/onGameStartedPatch.cs
Labels: Next Version/次期バージョン, Refactoring/リファクタリング

#867 Fix/MafiaKill
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
Labels: bug/バグ修正

#713 Feature/DisplayLastImpostor
  Modules/CustomRolesHelper.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/TaskAdderPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#854 CustomWinner, AdditionalWinnerをCustomRolesにキャスト
  Modules/RPC.cs
  Patches/ControlPatch.cs
  Patches/OutroPatch.cs
  main.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#869 Fix/GuardAndKill-fix
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正

#877 解像度を変えた時にボタンが全て左下にいく問題を修正
  Modules/ModUpdater.cs
Labels: bug/バグ修正

#886 Refact/issues
  Modules/ExtendedPlayerControl.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/OutroPatch.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#892 ウォーロックキル以外全てRpcMurderPlayerに差し戻し
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Roles/FireWorks.cs
Labels: bug/バグ修正, change/仕様変更

#814 isDeadがfalseの時のみ死因を設定するように
  Modules/GameState.cs
  Modules/Utils.cs
Labels: change/仕様変更

#815 テロリストがキルされたときの死因設定を修正
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#893 Revert "isDeadがfalseの時のみ死因を設定するように"
  Modules/GameState.cs
  Modules/Utils.cs
Labels: documentation/文書の変更

#885 対応AmongUsバージョンを表記
  README-EN.md
  README.md
Labels: documentation/文書の変更

#875 インポスター、マッドメイト系役職の色を毎回追加しなくてもいいように変更
  main.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#894 Doc/AddSpeedBoosterLog
  Modules/ExtendedPlayerControl.cs
Labels: documentation/文書の変更

#880 名前にTOHが入っていないと公開ルームにできないように修正
  Patches/ClientPatch.cs
  Resources/string.csv
Labels: bug/バグ修正, change/仕様変更

#890 ウォッチャーのTaskTextPrefixを修正
  Patches/HudPatch.cs
Labels: bug/バグ修正

#898 CSVで例外が起きた際に問題個所を行数で表示
  Modules/Translator.cs
Labels: change/仕様変更

#910 Feature/ColoredOnOff
  Modules/CustomOption.cs
  Modules/Utils.cs
  Resources/string.csv
Labels: new feature/新機能, Visual/ビジュアル

#882 Feature/SerialKillerClass
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/SerialKiller.cs
  main.cs
Labels: Refactoring/リファクタリング, Class/クラス化

#911 シェイプマスター削除
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Patches/ChatCommandPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  main.cs
Labels: removed/機能削除

#913 弾を撃ち切ったスナイパーのシェイプテキストを変身に変更
  Patches/HudPatch.cs
  Resources/string.csv
  Roles/Sniper.cs
Labels: change/仕様変更, Visual/ビジュアル

#914 StandardHASで扉閉め出来ないように
  Patches/ShipStatusPatch.cs
Labels: change/仕様変更

#916 README-ENでトラッパーの設定がディクテーターの下に合った問題を修正
  README-EN.md
Labels: bug/バグ修正, documentation/文書の変更

#912 Feature/TimeThiefClass
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
  Roles/TimeThief.cs
  main.cs
Labels: new feature/新機能, Class/クラス化

#921 Feature/MareClass
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
  Roles/Mare.cs
Labels: new feature/新機能, Class/クラス化

#925 Fix/Sheriff-ResetPlayerCam
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#927 Feature/AntiBlackout
  Modules/AntiBlackout.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#920 メイヤーの守護ブロックを削除
  Patches/PlayerContorolPatch.cs
Labels: removed/機能削除

#806 Doc/ReviseREADME-EN
  README-EN.md
  Resources/string.csv
Labels: documentation/文書の変更, WIP/開発途中

#931 ジャッカルがキーボードでキルしたりベントに入ったりできるように
  Patches/ControlPatch.cs
Labels: bug/バグ修正

#936 誤字を修正
  Modules/AntiBlackout.cs
Labels: bug/バグ修正

#939 PSやXbox等でウェルカムメッセージが届かない問題を改善
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正, change/仕様変更

#938 テンプレート送信時に例外が発生する問題を修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#941 fix/AntiBlackout-1
  Modules/AntiBlackout.cs
  Patches/ExilePatch.cs
Labels: bug/バグ修正

#947 Translateクラスとリファクタリング
  Modules/Translator.cs
Labels: Refactoring/リファクタリング

#948 中国語翻訳を追加
  README-EN.md
  README.md
  Resources/string.csv
Labels: documentation/文書の変更
