Repository tukasa0001/TownOfHost, pull requests merged in 2022-08, with the labels that each got.

#946 Change/OnOffColor
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Resources/string.csv
Labels: change/仕様変更, Visual/ビジュアル

#950 TChinese追加
  Resources/string.csv
Labels: Add Translation/翻訳追加

#951 clean up translation README(EN)の更新
  README-EN.md
Labels: documentation/文書の変更

#954 翻訳を追加
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: Add Translation/翻訳追加

#955 起動時にtemplate.txtがなければ自動作成
  main.cs
Labels: change/仕様変更

#963 renameコマンドの修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#964 ゲーム設定の秘匿オプションを追加
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Resources/string.csv
Labels: new feature/新機能

#791 Feature/DisableAdmin
  Modules/DisableDevice.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/Devices/Admin.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: new feature/新機能

#909 Refact/LadderDeathPatch
  Patches/ExilePatch.cs
  Patches/LadderPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
Labels: Refactoring/リファクタリング

#647 [Not Merge]開発者へのリンクの変更
  README-EN.md
  README.md
Labels: documentation/文書の変更

#968 unity-libsの参照の削除 (fix/unity-libs)
  TownOfHost.csproj
Labels: removed/機能削除

#944 Fix/AntiBlackout-2
  Modules/AntiBlackout.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正, new feature/新機能

#937 タイムシーフのCurrentKillCooldown削除
  Roles/TimeThief.cs
Labels: bug/バグ修正

#970 3.0.0にバージョンアップ
  main.cs
Labels: VerUp/バージョンアップ

#873 Refact/onGameStartedPatch
  Patches/onGameStartedPatch.cs
Labels: Refactoring/リファクタリング

#876 Feature/BountyHunterClass
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/BountyHunter.cs
  main.cs
Labels: Refactoring/リファクタリング, Class/クラス化

#919 チャットの名前色をロールカラーに変更
  Patches/ChatBubblePatch.cs
Labels: new feature/新機能, Visual/ビジュアル

#917 MeetingHudPatch内の名前処理をリファクタ
  Patches/MeetingHudPatch.cs
Labels: Refactoring/リファクタリング

#901 Feature/SabotageMasterClass
  Modules/OptionHolder.cs
  Patches/ShipStatusPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/SabotageMaster.cs
Labels: bug/バグ修正, documentation/文書の変更, Class/クラス化

#945 Feature/GM
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#922 replace/BlockKilling
  Modules/ExtendedPlayerControl.cs
  Patches/CredentialsPatch.cs
  Patches/NoBlackoutPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正, Refactoring/リファクタリング, change/仕様変更

#977 CSV_Fix SChinese and TChinese
  Resources/string.csv
Labels: Add Translation/翻訳追加

#979 fix getRoleName _Translation
  Modules/Utils.cs
Labels: bug/バグ修正

#933 README 暗転対策自殺の注釈分を追記
  README-EN.md
  README.md
Labels: documentation/文書の変更

#983 TChinese csv update
  Resources/string.csv
Labels: Add Translation/翻訳追加

#982 エスクキューショナーが抜けた際にTOHクライアントがキックされる問題を修正
  Modules/RPC.cs
Labels: bug/バグ修正

#990 mainブランチ以外で日本でなければオンライン禁止
  Patches/ClientPatch.cs
Labels: new feature/新機能

#994 Fix speed booster action
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
Labels: bug/バグ修正

#995 Fix/AntiBlackout-3
  Modules/AntiBlackout.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#1010 killerが死んでいる場合キルをキャンセル
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#1013 ID被りを修正
  Modules/OptionHolder.cs
Labels: bug/バグ修正

#988 GMがラバーズになる問題を修正
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#1015 GMがいる試合でラバーズが割り当てられない問題を修正
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#1016 テロリストの死因の問題を修正
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#1009 Feature/EveryoneDied(全滅エンド)
  Modules/RPC.cs
  Patches/CheckGameEndPatch.cs
  Patches/OutroPatch.cs
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#987 ウィッチの呪いキルでエクスキューショナーの役職が変わらない問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#1017 mod入りクライアントのアドミン無効化の条件が反転している問題を修正
  Patches/Devices/Admin.cs
Labels: bug/バグ修正

#884 Feature/EgoistClass
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/IntroPatch.cs
  Patches/OutroPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  Roles/Egoist.cs
  Roles/TeamEgoist.cs
Labels: new feature/新機能, Refactoring/リファクタリング, Class/クラス化

#1018 GMが生きている判定になってることで起きる問題を修正
  Patches/IntroPatch.cs
Labels: bug/バグ修正

#1022 IsActiveメソッドを改良
  Modules/Utils.cs
Labels: change/仕様変更

#1005 Change/Delete10-90%
  Modules/OptionHolder.cs
Labels: change/仕様変更

#1025 GMが有効の時にmodクライアントが全員会議中に役職が表示される問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#1008 全員生存時の会議時間オプションを追加
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Resources/string.csv
Labels: new feature/新機能

#1027 Fix/MadmatesCanFixSabotages
  Patches/ShipStatusPatch.cs
Labels: bug/バグ修正

#1032 Doc/AddDeveloperLink
  README-EN.md
  README.md
  README_SChinese.md
Labels: documentation/文書の変更

#1033 Fix/Vampireに噛まれたプレイヤーが切断すると会議が始まらない
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#1026 Fix/Puppeteer_CantVisibleMark
  Patches/PlayerContorolPatch.cs
  main.cs
Labels: bug/バグ修正

#1028 Remove/IsActiveLog
  Modules/Utils.cs
Labels: documentation/文書の変更, removed/機能削除

#1037 Feature/Fork Config
  Helpers.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ClientPatch.cs
  Patches/CredentialsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/TaskAdderPatch.cs
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#1041 Verup/v2.2.2
  TownOfHost.csproj
  main.cs
Labels: VerUp/バージョンアップ

#999 スピード周りとｽﾋﾟﾌﾞのタスク量で効果発揮するように仕様変更
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/PlayerContorolPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  Roles/Mare.cs
  main.cs
Labels: bug/バグ修正, change/仕様変更

#1023 コンフリクト解消ミスで消えたStandardHASの要素を復活
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正

#1019 Change/GM_Outro
  Patches/OutroPatch.cs
Labels: new feature/新機能, change/仕様変更

#1024 サーバーをだます処理を2秒遅延
  Patches/IntroPatch.cs
Labels: change/仕様変更

#1048 OptionShowerとチャットコマンドでChildrenを自動で追加
  Modules/OptionShower.cs
  Modules/Utils.cs
Labels: Refactoring/リファクタリング, Visual/ビジュアル

#1044 Doc/japanese option name
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/LadderPatch.cs
  README-EN.md
  Resources/string.csv
  Roles/FireWorks.cs
Labels: documentation/文書の変更

#1034 Feature/SheriffKillOption
  Resources/string.csv
  Roles/Sheriff.cs
Labels: change/仕様変更, Visual/ビジュアル

#1049 Doc/neutral intro
  Patches/IntroPatch.cs
  README-EN.md
  README.md
  README_SChinese.md
  Resources/string.csv
Labels: documentation/文書の変更

#1056 Feature/RpcGuardAndKill_DisableGAIcon
  Modules/ExtendedPlayerControl.cs
Labels: change/仕様変更, Fix/修正

#1052 Feature/ChangePresetName
  Modules/CustomOption.cs
  Modules/OptionHolder.cs
  Patches/GameOptionsMenuPatch.cs
  main.cs
Labels: new feature/新機能

#1061 Doc/string jackal
  Resources/string.csv
Labels: documentation/文書の変更

#1062 Feature/task text color
  Modules/Utils.cs
Labels: Visual/ビジュアル

#1063 変化先がクルー設定のエクスキューショナーがMODでも変化前にタスクをできるように
  Modules/Utils.cs
Labels: Fix/修正

#1055 [TAKU]ボタン同期モードで会議開始時に名前をtestに変えないように
  Patches/MeetingHudPatch.cs
Labels: removed/機能削除, TAKU GG

#1054 [TAKU]ロビーでアウトラインに色付けされる問題を修正(Desync組)
  Patches/HudPatch.cs
Labels: Fix/修正, TAKU GG

#907 [TAKU]Change/TaskTextPrefix
  Patches/HudPatch.cs
  Resources/string.csv
Labels: new feature/新機能, change/仕様変更, TAKU GG
