Repository tukasa0001/TownOfHost, pull requests merged in 2022-05, with the labels that each got.

#454 [v2.0.0]Fix/deathReasonRpc
  Modules/GameState.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#447 Feature/Comms_TaskText
  Modules/Utils.cs
  Patches/ShipStatusPatch.cs
Labels: new feature/新機能

#457 RandomMapsの中身が空の時はマップ変更をせずにゲームを開始させるように変更
  Patches/GameStartManagerPatch.cs
Labels: bug/バグ修正

#463 [v2.0.0]Fix/InvalidRPC
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#453 [v2.0.0]Fix/fixed update
  Modules/GameState.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#458 一部役職説明で、役職名が出ない問題を修正
  Patches/ChatCommandPatch.cs
Labels: bug/バグ修正

#460 試合中にlastrolesを使った際の警告の英語訳追加
  Modules/Utils.cs
  Resources/string.csv
Labels: documentation/文書の変更, new feature/新機能

#459 ShowHelpに英語訳を追加
  Modules/Utils.cs
  Resources/string.csv
Labels: documentation/文書の変更, new feature/新機能

#449 [v2.0.0]バージョン一覧のコマンドを追加
  Patches/ChatCommandPatch.cs
Labels: new feature/新機能

#467 Re:ShowHelpに英語訳を追加
  Modules/Utils.cs
  Resources/string.csv
Labels: documentation/文書の変更, new feature/新機能

#466 [v2.0.0]Feature/auto-updater
  Modules/ModUpdater.cs
  Patches/ClientPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/PlayerContorolPatch.cs
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#342 [v2.0.0] Feature/SnitchArrow
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#414 [v2.0.0]Feature/Puppeteer
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: documentation/文書の変更, new role/新役職

#470 Discordボタンを追加
  Modules/ModUpdater.cs
Labels: new feature/新機能

#426 [v2.0.0]feature/SabotageTimeControl
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/SabotageSystemtPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: new feature/新機能

#455 Feature/Re_Doctor
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#471 Feature/ghost-can-see-other-roles
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#474 [v2.0.0]汎用Isメソッド
  Modules/ExtendedPlayerControl.cs
Labels: new feature/新機能

#475 [v2.0.0]MODクライアントでAliveImpostorsが初期化されない点の修正
  Patches/ShipStatusPatch.cs
Labels: bug/バグ修正

#464 feature/Dictator 独裁者
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ChatCommandPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#461 Feature/Executioner
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: documentation/文書の変更, new role/新役職

#423 [v2.0.0]Feature/StandardHAS
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#483 Fix/Standard_HAS
  Modules/OptionHolder.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
Labels: bug/バグ修正

#477 Isメゾット作成(RoleType版)
  Modules/ExtendedPlayerControl.cs
Labels: new feature/新機能

#484 fix/ReportDeadBody
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#486 HideAndSeekの役職名にHASをつけるように変更
  Modules/CustomRolesHelper.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/OutroPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
  main.cs
Labels: documentation/文書の変更

#442 Change/ArsonistWinTrigger
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: change/仕様変更

#488 fix/HideAndSeek
  Modules/RPC.cs
  Patches/CheckGameEndPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
  main.cs
Labels: bug/バグ修正, Refactoring/リファクタリング

#485 Isメゾットを適応(RoleType版)
  Patches/IntroPatch.cs
  Patches/OutroPatch.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#476 Isメゾットに各役職を適応
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/CheckGameEndPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
Labels: documentation/文書の変更, Refactoring/リファクタリング

#491 霊界が投票先を見れるオプションを追加
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Resources/string.csv
Labels: new feature/新機能

#378 [v2.0.0]lovers
  Modules/Calculation.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#492 Feature/TranslationReplacer
  Modules/CustomOption.cs
  Modules/Translator.cs
Labels: new feature/新機能

#456 [v2.0.0]Fix/VampireKill
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Resources/string.csv
  main.cs
Labels: bug/バグ修正

#496 [v2.0.0]isTrapper()をIs()に置き換え
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#498 [v2.0.0]Fix/LateTaskの多重起動に対応
  Modules/LateTask.cs
Labels: bug/バグ修正

#478 [v2.0.0]Feature/fire works
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  Roles/FireWorks.cs
  main.cs
Labels: new role/新役職

#465 Fix/KillCooldown_AfterMeeting
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/ExilePatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#497 [v2.0.0]Loversじゃない人が心中する不具合修正
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#479 [v2.0.0]新役職/スナイパー
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  Roles/Sniper.cs
  main.cs
Labels: new role/新役職

#494 Feature/MoreTaskOptions-new
  Modules/GameState.cs
  Modules/OptionHolder.cs
  Patches/TaskAssignPatch.cs
  Resources/string.csv
Labels: new feature/新機能

#502 ログの追加とリファクタリング
  Helpers.cs
  Modules/Debugger.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/LateTask.cs
  Modules/ModUpdater.cs
  Modules/NameColorManager.cs
  Modules/RPC.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ClientPatch.cs
  Patches/ControlPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Sniper.cs
Labels: Refactoring/リファクタリング

#482 Fix/SchrodingerCat_Setting
  Modules/RPC.cs
  Patches/ExilePatch.cs
  README-EN.md
  README.md
Labels: bug/バグ修正, new feature/新機能

#503 会議の投票先ログと修正
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正, Refactoring/リファクタリング

#499 Feature/VisibleExecutionerTarget
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: new feature/新機能

#507 [v2.0.0]Fix/lovers win
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#450 [v2.0.0]Feature/Mare
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: help wanted/サポートが必要, new role/新役職

#506 RPCの受信ログの追加
  Modules/RPC.cs
  main.cs
Labels: new feature/新機能

#481 [2.0.0]Feature/TimeThief
  Modules/CustomRolesHelper.cs
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Modules/RPC.cs
  Patches/ChatCommandPatch.cs
  Patches/ExilePatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new role/新役職

#504 Fix/more task options settings shower
  Modules/CustomOption.cs
  Modules/OptionHolder.cs
  Modules/Utils.cs
Labels: bug/バグ修正

#490 feature/MayorPortableButton
  Modules/ExtendedPlayerControl.cs
  Modules/OptionHolder.cs
  Patches/ExilePatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
  main.cs
Labels: new feature/新機能

#509 RpcGuardAndKillのガード通知を修正
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#508 ログに行数とファイル名を追加
  Modules/Debugger.cs
  Patches/PlayerContorolPatch.cs
Labels: Refactoring/リファクタリング

#510 プレイヤー退出時の例外を修正
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#514 会議ごとにパペッティアのDicを削除するように
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#512 トロール勝利の適正化
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#519 ログのゲーム内同時出力
  Modules/Debugger.cs
  Patches/ControlPatch.cs
Labels: new feature/新機能

#522 シェイプシフト中に元の名前が表示される問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#523 MODクライアントか判定するメソッドの追加
  Modules/ExtendedPlayerControl.cs
Labels: new feature/新機能

#520 feature/SpecificMurderPlayer
  Modules/ExtendedPlayerControl.cs
Labels: new feature/新機能

#515 Fix/schrodinger cat at snipe
  Modules/ExtendedPlayerControl.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  Roles/Sniper.cs
Labels: bug/バグ修正

#521 シェイプシフター系の名前問題
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#524 Fix/MayorPortableButton
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/PlayerContorolPatch.cs
  README-EN.md
  README.md
  Resources/string.csv
Labels: bug/バグ修正, documentation/文書の変更, change/仕様変更

#526 InGame判定をカスタム役職決定後にセットするように修正
  Modules/GameState.cs
  Patches/IntroPatch.cs
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#527 SKマッドメイトを作るタイミングを間違っていたため修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#528 MODクライアントの例外を修正
  Modules/RPC.cs
  Modules/Utils.cs
Labels: bug/バグ修正

#532 Mayorの投票数を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#531 花火職人のフェーズの翻訳追加
  Resources/string.csv
  Roles/FireWorks.cs
Labels: documentation/文書の変更, new feature/新機能

#530 Dictatorがスキップや無投票の時に自殺する問題を修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#534 ログの詳細表示を標準で無効に
  main.cs
Labels: change/仕様変更

#513 デバッグモード可視化
  Patches/CredentialsPatch.cs
Labels: documentation/文書の変更, new feature/新機能

#533 シールド系のログを追加
  Patches/PlayerContorolPatch.cs
Labels: new feature/新機能

#525 Fix/arsonist doused count
  Modules/Utils.cs
  Patches/HudPatch.cs
  Patches/PlayerContorolPatch.cs
  Roles/Sniper.cs
Labels: bug/バグ修正, Refactoring/リファクタリング

#538 F11で解像度を変更できるように
  Patches/ControlPatch.cs
Labels: new feature/新機能

#542 会議と同時にボタン入った時の対策
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#543 [v2.0.0]Feature/lovers recall
  Patches/PlayerContorolPatch.cs
Labels: change/仕様変更

#544 ラバーズ勝利の生存判定を修正
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#546 Recall例外の修正
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#545 RpcGuardAndKill()周りの修正
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: bug/バグ修正

#547 エゴイストの勝利が正常に表示されない問題を修正
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#548 nullチェックの追加
  Modules/ExtendedPlayerControl.cs
  Modules/RPC.cs
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/IntroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/Sniper.cs
Labels: bug/バグ修正

#516 ReadMeの修正
  README-EN.md
  README.md
Labels: documentation/文書の変更

#518 ログのレイアウトがずれていた問題を修正
  Modules/Utils.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
Labels: bug/バグ修正

#552 ArsonistがSchrodingerCatに塗るときの挙動修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#551 切断したプレイヤーの死因が塗り替えられていた問題を修正
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#555 ロビーでバージョンごとに名前を変更
  Patches/PlayerContorolPatch.cs
Labels: new feature/新機能

#556 キルクールの初期化追加
  Patches/onGameStartedPatch.cs
Labels: bug/バグ修正, new feature/新機能

#557 シェイプシフト時のログをクライアントでも出すように
  Patches/PlayerContorolPatch.cs
Labels: change/仕様変更

#558 クレジットの位置を調整
  Patches/CredentialsPatch.cs
Labels: bug/バグ修正

#550 塗られた人が殺された時の塗りカウントが正常に動作していなかった問題を修正
  Modules/ExtendedPlayerControl.cs
Labels: bug/バグ修正

#563 最初の会議が終わるとシュレ猫の陣営が確定で変わる問題を修正
  Patches/ExilePatch.cs
Labels: bug/バグ修正

#560 ログのタグ付けを強制
  Modules/Debugger.cs
  Modules/OptionHolder.cs
  Modules/TextureManager.cs
  Patches/TaskAssignPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/FireWorks.cs
  main.cs
Labels: change/仕様変更

#566 .editorconfigを編集
  .editorconfig
  .vscode/settings.json
Labels: Refactoring/リファクタリング

#567 リファクタリング
  Helpers.cs
  Modules/CustomOption.cs
  Modules/CustomRolesHelper.cs
  Modules/Debugger.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/LateTask.cs
  Modules/ModUpdater.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/RPC.cs
  Modules/TextureManager.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatBubblePatch.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ControlPatch.cs
  Patches/DisconnectPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/FireWorks.cs
  Roles/Sniper.cs
  main.cs
Labels: Refactoring/リファクタリング

#568 メソッド名をUCCに統一
  Helpers.cs
  Modules/CustomOption.cs
  Modules/CustomRolesHelper.cs
  Modules/Debugger.cs
  Modules/ExtendedPlayerControl.cs
  Modules/GameState.cs
  Modules/LateTask.cs
  Modules/ModUpdater.cs
  Modules/NameColorManager.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/RPC.cs
  Modules/TextureManager.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatBubblePatch.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ClientPatch.cs
  Patches/ControlPatch.cs
  Patches/CredentialsPatch.cs
  Patches/DisconnectPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HudPatch.cs
  Patches/IntroPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/NoBlackoutPatch.cs
  Patches/OutroPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/PlayerJoinAndLeftPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/TaskAssignPatch.cs
  Patches/UsablesPatch.cs
  Patches/onGameStartedPatch.cs
  Roles/FireWorks.cs
  Roles/Sniper.cs
  main.cs
Labels: Refactoring/リファクタリング

#572 トロール勝利の時に、狐を追加勝利していた問題を修正
  Patches/OutroPatch.cs
Labels: bug/バグ修正

#573 fix/OnPlayerLeft
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#574 Fix/KillWithGuard
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正, documentation/文書の変更, Refactoring/リファクタリング

#575 AirshipMeetingCheckを削除
  Modules/ExtendedPlayerControl.cs
  Patches/PlayerContorolPatch.cs
  Patches/onGameStartedPatch.cs
  main.cs
Labels: removed/機能削除

#578 Fix/MayorPortableButton
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#577 リファクタリング
  Helpers.cs
  Modules/CustomOption.cs
  Modules/CustomRolesHelper.cs
  Modules/Debugger.cs
  Modules/ExtendedPlayerControl.cs
  Modules/LateTask.cs
  Modules/ModUpdater.cs
  Modules/NameColorManager.cs
  Modules/OptionShower.cs
  Modules/RPC.cs
  Modules/Translator.cs
  Modules/Utils.cs
  Patches/ChatBubblePatch.cs
  Patches/ChatCommandPatch.cs
  Patches/CheckGameEndPatch.cs
  Patches/ClientOptionsPatch.cs
  Patches/ControlPatch.cs
  Patches/ExilePatch.cs
  Patches/GameOptionsMenuPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/HudPatch.cs
  Patches/JoinGameButtonPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/PlayerContorolPatch.cs
  Patches/RecomputeTaskPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/TaskAdderPatch.cs
  Patches/UsablesPatch.cs
  Roles/FireWorks.cs
  Roles/Sniper.cs
  main.cs
Labels: Refactoring/リファクタリング

#581 if文とreturnを整理
  Modules/CustomOption.cs
  Modules/ExtendedPlayerControl.cs
  Modules/ModUpdater.cs
  Modules/OptionHolder.cs
  Modules/OptionShower.cs
  Modules/Utils.cs
  Patches/CredentialsPatch.cs
  Patches/GameStartManagerPatch.cs
  Patches/IntroPatch.cs
  Patches/MeetingHudPatch.cs
  Patches/ShipStatusPatch.cs
  Patches/UsablesPatch.cs
  Roles/FireWorks.cs
Labels: Refactoring/リファクタリング

#582 シュレ猫がキルされたときに死ぬ問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#583 シュレ猫をMafiaでも変化させられる問題を修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#585 RpcSetNameExにログ出力追加
  Modules/ExtendedPlayerControl.cs
Labels: new feature/新機能

#589 editorconfigを修正
  .editorconfig
Labels: change/仕様変更

#584 Feature/RecallDespawn
  Patches/MeetingHudPatch.cs
Labels: new feature/新機能

#590 コピー&ペーストに対応
  Patches/ChatControlPatch.cs
Labels: new feature/新機能

#592 recallのコミット抜けを修正
  Patches/PlayerContorolPatch.cs
Labels: bug/バグ修正

#599 ラバーズが抜けた後にラバーズを削除するように修正
  Patches/PlayerJoinAndLeftPatch.cs
Labels: bug/バグ修正

#598 会議時シェイプシフト中の名前になることがある
  Patches/MeetingHudPatch.cs
  Patches/ShipStatusPatch.cs
Labels: bug/バグ修正

#601 チャットの処理を変更
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
Labels: change/仕様変更

#602 Feature/ResetAbilityCooldownMethod
  Modules/ExtendedPlayerControl.cs
  Patches/ControlPatch.cs
Labels: new feature/新機能, Next Version/次期バージョン

#603 MOD構成に異常がある場合の処理を追加
  Modules/ModUpdater.cs
  Patches/ClientPatch.cs
  Patches/PlayerContorolPatch.cs
  Resources/string.csv
Labels: new feature/新機能, change/仕様変更

#608 コマンドの改名と修正
  Modules/Utils.cs
  Patches/ChatCommandPatch.cs
  Patches/ControlPatch.cs
  Resources/string.csv
Labels: bug/バグ修正, change/仕様変更

#607 READMEの追加と修正
  README-EN.md
  README.md
Labels: documentation/文書の変更

#611 バウンティハンターのcsv修正
  Resources/string.csv
Labels: bug/バグ修正
